export const API_URLS = {
  BASE_URL: "http://localhost:5000",
  REGISTER: "/auth/register",
  CHECK_AUTH: "/checkAuth/check",
  ADD_INFO: "/infos/add",
  ADD_PREFERENCES: "/preferences/add",
  GET_PREFERENCES_BY_ID: "/preferences",
  GET_USER_BY_ID: "/user",
  UPDATE_USER_BY_ID: "/user",
  CHECK_PASSWORD:"/user/check-password",
  GET_USER_LIST: "/user/list",
  GET_INFO_BY_USER_ID: "/infos",
  GET_INFO_LIST: "/infos/list",
  LOGIN: "/auth/login",
  ADD_PHOTO: "/photos/add",
  ADD_PROFILE_PHOTO: "/photos/upload-photo",
  GET_PHOTO: "/photos",
  DELETE_PHOTO: "/photos/delete",
  EDIT_INFO: "/infos",
  LIKE_USER: "/likes/add",
  GET_LIKED_USER: "/likes/by-user",
  REMOVE_LIKE: "/likes",
  VISIT_USER: "/visits/add",
  ALL_VISITED_USER: "/visits/visiter",
  ALL_VISITER_USER: "/visits/visited",
  ALL_LIKER_USER: "/likes/liked-by",
  SEND_INTEREST: "/interests/add",
  GET_INTERESTS: "/interests/list",
  GET_ALL_INTERESTS: "/interests/full-list",
  UPDATE_INTERESTS_STATUS: "/interests",
  GET_ALL_CONTACTS:"/messages/users",
  GET_ALL_MESSAGES:"/messages/conversation",
  SEND_MESSAGE:"/messages/send",
  UPDATE_MESSAGE_STATUS:"/messages/mark",
  CONNECT_USER:"/connections/add",
};
