export const privateRoutes = [
  { path: "/home", component: "Home" },
  { path: "/profile-creation/upload-photo", component: "CreateProfile" },
  { path: "/hobby-interest", component: "Hobby" },
  { path: "/profile-preview", component: "ProfilePreview" },
  { path: "/my-profile", component: "MyProfile" },
  { path: "/my-photos", component: "MyPhotos" },
  { path: "/matches/all-matches", component: "Matches" },
  { path: "/matches/all-matches/:id", component: "UserProfilePage" },
  { path: "/matches/photo-matches", component: "Matches" },
  { path: "/matches/shortlisted-by-you", component: "ShortlistOfUser" },
  { path: "/matches/viewed-you", component:"Viewed" },
  { path: "/matches/shortlisted-you", component: "ShortListedYou" },
  { path: "/matches/profiles-with-horoscope", component: "Matches" },
  { path: "/matches/hobby-matches", component: "Matches" },
  { path: "/settings", component: "Settings" },
  { path: "/partner-preferences", component: "PartnerPreferences" },
  { path: "/profile-creation/step/:step", component: "CreateProfile" },
  { path: "/profile-creation/about-me", component: "CreateProfile" },
  { path: "/profile-creation/family-details", component: "CreateProfile" },
  { path: "/inbox", component: "Inbox" },
];
