export const ages = Array.from({ length: 70 - 18 + 1 }, (_, i) => 18 + i);
export const degrees = [
  "Bachelor's - Engineering / Computer Science",
  "Master's - Engineering / Computer Science",
  "Bachelor's - Arts / Science / Commerce",
  "Master's - Arts / Science / Commerce",
  "Bachelor's - Management",
  "Master's - Management",
  "Bachelor's - Medicine - General / Dental / Surgeon",
  "Master's - Medicine - General / Dental / Surgeon",
  "Bachelor's - Pharmacy / Nursing or Health Sciences",
  "Master's- Pharmacy / Nursing or Health Sciences",
  "Bachelor's - Legal",
  "Master's - Legal",
  "Finance - ICWAI / CA / CS/ CFA",
  "Civil Services",
  "Doctorates",
  "Diploma /Polytechnic",
  "Higher Secondary / Secondary",
];
export const dosh = ["Yes", "No", "Doesn't Matter"];
export const employedIn = [
  "Any",
  "Private Company",
  "Government / Public Sector",
  "Defense / Civil Services",
  "Business / Self Employed",
  "Not Working",
];
export const drinkingHabits = [
  "Doesn't matter",
  "Never drinks",
  "Drinks socially",
  "Drinks regularly",
];
export const eatingHabits = [
  "Doesn't matter",
  "Vegetarian",
  "Non Vegetarian",
  "Eggetarian",
];
export const smokingHabits = [
  "Doesn't matter",
  "Never smokes",
  "Smokes socially",
  "Smokes regularly",
];
export const states = [
  "Any",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];
export const rashi = [
  "Any",
  "Mesh (Aries)",
  "Vrishabh (Taurus)",
  "Mithun (Gemini)",
  "Karka (Cancer)",
  "Simha (Leo)",
  "Kanya (Virgo)",
  "Tula (Libra)",
  "Vrischik (Scorpio)",
  "Dhanu (Sagittarius)",
  "Makar (Capricorn)",
  "Kumbh (Aquarius)",
  "Meen (Pisces)",
];
export const physicalStatus = [
  "Normal",
  "Physicaly Challanged",
];
export const maritalStatuses = [
  "Any",
  "Never married",
  "Widowed",
  "Divorced",
  "Awaiting Divorce",
];
export const star = [
  "Any",
  "Ashwini",
  "Bharani",
  "Krittika",
  "Rohini",
  "Mrigashira",
  "Ardra",
  "Punarvasu",
  "Pushya",
  "Ashlesha",
  "Magha",
  "Purva Phalguni",
  "Uttara Phalguni",
  "Hasta",
  "Chitra",
  "Swati",
  "Vishakha",
  "Anuradha",
  "Jyeshtha",
  "Mula",
  "Purva Ashadha",
  "Uttara Ashadha",
  "Shravana",
  "Dhanishta",
  "Shatabhisha",
  "Purva Bhadrapada",
  "Uttara Bhadrapada",
  "Revati",
];
export const professions = [
  "Any",
  "Chartered Accountant",
  "Investment Banker",
  "Financial Analyst",
  "Auditor",
  "HR Manager",
  "Administrative Officer",
  "Recruitment Specialist",
  "Payroll Executive",
  "Copywriter",
  "Film Director",
  "Radio Jockey",
  "Media Planner",
  "Agronomist",
  "Farm Manager",
  "Horticulturist",
  "Agricultural Scientist",
  "Commercial Pilot",
  "Cabin Crew",
  "Air Traffic Controller",
  "Aircraft Maintenance Engineer",
  "Architect",
  "Interior Designer",
  "Urban Planner",
  "Landscape Architect",
  "Graphic Designer",
  "3D Animator",
  "Illustrator",
  "Web Designer",
  "Digital Marketing Specialist",
  "Sales Executive",
  "Brand Manager",
  "Market Research Analyst",
  "Marine Engineer",
  "Deck Officer",
  "Radio Officer",
  "Chief Engineer",
  "IAS Officer",
  "IPS Officer",
  "IFS Officer",
  "Income Tax Officer",
  "Physicist",
  "Biotechnologist",
  "Microbiologist",
  "Environmental Scientist",
  "Business Consultant",
  "Project Manager",
  "Compliance Officer",
  "Operations Head",
  "Process Associate",
  "Customer Support Executive",
  "Data Analyst",
  "Quality Analyst",
];
export const subCommunity =[
    "Any",
    "Bramhan",
    "Mahisya",
    "Kayastha",
]
export const languages = [
  "Hindi" ,
  "English" ,
  "Bengali" ,
  "Marathi" ,
  "Tamil" ,
  "Telugu" ,
  "Gujarati" ,
  "Kannada" ,
  "Punjabi" ,
  "Malayalam" ,
];
