export const degrees = [
  "Bachelor's - Engineering / Computer Science",
  "Master's - Engineering / Computer Science",
  "Bachelor's - Arts / Science / Commerce",
  "Master's - Arts / Science / Commerce",
  "Bachelor's - Management",
  "Master's - Management",
  "Bachelor's - Medicine - General / Dental / Surgeon",
  "Master's - Medicine - General / Dental / Surgeon",
  "Bachelor's - Pharmacy / Nursing or Health Sciences",
  "Master's- Pharmacy / Nursing or Health Sciences",
  "Bachelor's - Legal",
  "Master's - Legal",
  "Finance - ICWAI / CA / CS/ CFA",
  "Civil Services",
  "Doctorates",
  "Diploma /Polytechnic",
  "Higher Secondary / Secondary",
];
